sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '8'
cache:
- node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- npm run coverage && npm t -- --browsers=Firefox,BrowserStack_Edge,BrowserStack_Safari
env:
  global:
  - secure: ZrY5vzp2m7fvi7JT2sxU4b5NIvOSdtvc6QrtflFyRkyiVbdHsu5ut4WuZYbVX+nStqGT3wHtQMrzCClM/nULbEmLICnlOjSWm905qooEB2Jt6ZEQBI5FQdjaxkXhPGZdNgWjz13KaHJR8NkFo2c9f2gnrc0DICWQFMz/ABzsQt4RJrFD26cl3ElwBS31UaRNoRwoOaZZZZ+gkgkei0I3lXJ2S5i/yijNWKYA7yGy1+J5ATZJBUc0uXA5EETqlmNnUEurOEzj1CK3iGuaZsK7LBxNN1Ba6HPVVB8MLXcv9S4ILuUTzKH//ym0l319Iutc/VYfxXNtzLgAtPxLke8S2ggBpP29qZJ37+BaKLS8dGl1QaZ+7fHJdsEin+ZhyJQkqx22EtUQ/OLla0Yg5++cnBDTdjbeuurVSwuFyeu0ChdepK1FqbF3ihUR8+4yKA4NPtAiNNMafsuGXu2CV4KhFdazab8PjVmI6nMCuq79/J0IzmRxV7NfwaoEdgiNmk72k/GIAGfUQ6RuwyEHHGZRcl3kL1o5vRJefVh78S7Poa81dhCdbhvgp7k5LJ1r0ACpdF16fOlfnRAfLNhNJM0Nspnyy/GESpk/pYGnqmNV1x2ytm8g5MhpvzFiGXQtx9yxPzMVyj4XALKCTomwdHcpwtQ2OSo28wg+1mGvem89Rvc=
  - secure: TDrgvDyzz3me4jRp/mVX6gczMrOzUH0MGLmxlqMmtWMdm48hHuqOjz/xHo7yY2r0B0CXvej6QzGJ/iS8u4a7bFtyjMRKnJyrsHlJ1OJ1WaZSeQxSCf0O6C3SWftEvAoMx2kJuLHA6Z70JzrDSJstnM0gxItn1N3Am/pzHSsnrm1zdVTzHNRxUWeeb1T6XNA9h8JYNQHuGiveV+YyaqZ+6RChhvZylocvavFW5xNLwEJNavNuNhC6MxwFWMH9iOBqGJsNBLwQJ7oyo6FDsJB8Pi9QZuOze3VkedjTP6MOf8UpCTsITnV20yVr7l3ZV7CEQlSKn94HFX0FkvOaLF/gYFKZR2VeUlpnk1cHAg6OiD2RFAx757pQqD5DfFZHmftAaqBc783eDrehZrKMiWkWZoqqQq68ONCA5gKXVhyZG+pclR2HXBANYZ3ytQ1pQW64G2ExEilCw2bL+oI0tAcW9UGzEmdp/0+j/QW42PXHa3Ic4UH9+gzqVCxBX0en09kveNoG2LM8ZNM7Kp/NZLTHJ8R8JDBT0TbIJHxxmaKIOTQ8Ye2YRhucEGSKaq35/BKpwhqGfbNtX53C/Z+hxr0SF0m1Tm+sogNOD4ms/UWzTXF3czsIxzsNVMeCqs0YVhfJReqEQPUDfxcKJufl8hi4/N7QGBde5vBri+XNqbGOVco=
